name: Build APK per Chiara
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0' # Versione più recente e stabile
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installa dipendenze
        run: |
          pip install flet==0.82.2 httpx

      - name: Accetta licenze Android
        run: yes | flutter doctor --android-licenses

      - name: Build APK
        run: |
          # Il comando 'yes' risponde automaticamente "y" a ogni domanda di Flet
          yes | flet build apk

      - name: Carica l'APK finale
        uses: actions/upload-artifact@v4
        with:
          name: App_Per_Chiara
          path: build/apk/*.apk
